{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePluginDemo",
    "module": "plugins",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-unspecified.jar",
          "url": "plugins-unspecified.jar",
          "size": 13485,
          "sha512": "660661d6ddf4b4e4d68e3276732c18ffcb23cae27e857c5bf9aa660d925c32a01efba7d364b6b06c7cf392a8c38017b673645541b1da45bf910a9d4f1f55d63a",
          "sha256": "30bdaf9e585602ef60f700dd0e90aba562de13a2444db017d0ebb7d4bd18c4c4",
          "sha1": "9ae16826587c4aa5b8d44aa3efccac00ddfb660c",
          "md5": "08d9edf222a2825dafb14999c5800149"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-unspecified.jar",
          "url": "plugins-unspecified.jar",
          "size": 13485,
          "sha512": "660661d6ddf4b4e4d68e3276732c18ffcb23cae27e857c5bf9aa660d925c32a01efba7d364b6b06c7cf392a8c38017b673645541b1da45bf910a9d4f1f55d63a",
          "sha256": "30bdaf9e585602ef60f700dd0e90aba562de13a2444db017d0ebb7d4bd18c4c4",
          "sha1": "9ae16826587c4aa5b8d44aa3efccac00ddfb660c",
          "md5": "08d9edf222a2825dafb14999c5800149"
        }
      ]
    }
  ]
}
